### ISSUE TITLE
Mass Approval Stuck [Patched - Awaiting Testing]

### ISSUE THREAD

**Issue by DarianAmin** [LukeG294/Brainly_Extension#3]
**Describe the bug**

When selective, mass approving from the user answer page with a reserved question. The process "freezes" as it becomes stuck on the answer it cannot approve. This occurs without notifying you, so you don't realise that the ones underneath are yet to be done. 

**To Reproduce**

1. Go to users answer page with at least one question being reserved
2. mass approve all or at least some questions, including the reserved one. 

**Expected behavior**

To skip ones it is unable to complete and notify the user

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**

**Comment by LukeG294** [comment]
On it tonight!

**Comment by LukeG294** [comment]
Fixed for approval on answers. 
<img width="1174" alt="image" src="https://github.com/LukeG294/Brainly_Extension/assets/62516707/e77aee61-2849-40ea-a9c9-0dc98b68e2ab">

**Comment by LukeG294** [comment]
Areas to fix:

Questions

[] confirm
[] delete

Answers

[] afc
[] delete
[x] approve
[] unapprove
[] confirm

**Comment by LukeG294** [comment]
Releasing 0.0.93 now. Please confirm that this is only an issue for the unchecked items in the comment above.

**Comment by LukeG294** [comment]
This issue has been fixed. Please confirm once 0.0.93 is approved.

**Comment by DarianAmin** [comment]
I can confirm this issue is no longer present.
