### ISSUE TITLE
Quick Deleter Not Responding First Try [Patched - Awaiting Testing]

### ISSUE THREAD

**Issue by LukeG294** [LukeG294/Brainly_Extension#7]
**Describe the bug**

The quick deleter doesn't prompt after clicking a reason sometimes. 

**To Reproduce**

1. Go to the search, content, or homepage.
2. Click on a deletable question link.
4. Right click, hover Brainly Extension, click the reason

**Expected behavior**

A confirmation followed by a warn Y/N prompt should appear.

**Additional context**
Might be an issue with the background script disconnecting after a certain amount of time.

**Comment by LukeG294** [comment]
@Grayson03 Please confirm working in `0.0.97` without any issues including issues when clicking the buttons on the alert :)

**Comment by Grayson03** [comment]
It still doesn't work for me period - it will show up, but once I click a deletion reason, no prompt appears and I have to refresh to get it to fetch the permission

**Comment by LukeG294** [comment]
Feature pushed back, will return eventually.
